#!/usr/bin/env python3
additions = [
    # deserto
    (
        '<span class="section-tag">Peregrinação</span>\n      <h1 class="section-title">O Deserto, as Crises e a Morte de Moisés</h1>\n      <p class="section-lead">Quarenta anos de julgamento, fidelidade, falhas humanas e providência divina no deserto.</p>',
        '<span class="section-tag">Wilderness</span>\n      <h1 class="section-title">The Desert, the Crises, and the Death of Moses</h1>\n      <p class="section-lead">Forty years of judgment, faithfulness, human failure, and divine providence in the wilderness.</p>'
    ),
    (
        '<h2>A Estrutura de Números</h2>\n    <p>O livro de Números registra a geração condenada (capítulos 1–25) e a nova geração (capítulos 26–36). A tragédia central é a incredulidade em Cades-Barneia (Nm 13–14), que condena uma geração inteira a morrer no deserto. Hebreus 3–4 usa este evento como advertência escatológica: a incredulidade endurece o coração e impede a entrada no descanso de Deus.</p>',
        '<h2>The Structure of Numbers</h2>\n    <p>The book of Numbers records the condemned generation (chapters 1–25) and the new generation (chapters 26–36). The central tragedy is the unbelief at Kadesh-Barnea (Num 13–14), which condemns an entire generation to die in the wilderness. Hebrews 3–4 uses this event as an eschatological warning: unbelief hardens the heart and prevents entry into God\'s rest.</p>'
    ),
    ('<div class="timeline-period">Números 11</div>\n        <div class="timeline-title">Murmuração — O Desejo pela Carne</div>\n        <div class="timeline-text">Israel anseia pelos alimentos do Egito. YHWH envia codornizes em abundância — mas também uma praga. O lugar é chamado Quibrote-Taavá: "sepulcros da cobiça." O padrão é recorrente: ingratidão, queixa, juízo, misericórdia.</div>',
     '<div class="timeline-period">Numbers 11</div>\n        <div class="timeline-title">Grumbling — The Craving for Meat</div>\n        <div class="timeline-text">Israel craves the food of Egypt. YHWH sends quail in abundance — but also a plague. The place is called Kibroth-hattaavah: "graves of craving." The pattern is recurrent: ingratitude, complaint, judgment, mercy.</div>'),
    ('<div class="timeline-period">Números 12</div>\n        <div class="timeline-title">Rebelião de Aarão e Miriã</div>\n        <div class="timeline-text">A oposição ao casamento de Moisés com a mulher etíope e ao seu ministério exclusivo. YHWH defende Moisés, declarando-o único a quem fala "face a face, não por visões" (Nm 12.6–8). Miriã é castigada com lepra; Moisés intercede por ela.</div>',
     '<div class="timeline-period">Numbers 12</div>\n        <div class="timeline-title">The Rebellion of Aaron and Miriam</div>\n        <div class="timeline-text">Opposition to Moses\'s marriage to the Cushite woman and to his exclusive ministry. YHWH defends Moses, declaring him the only one to whom he speaks "face to face, not in riddles" (Num 12:6–8). Miriam is struck with leprosy; Moses intercedes for her.</div>'),
    ('<div class="timeline-period">Números 13–14</div>\n        <div class="timeline-title">Os Doze Espias — A Crise de Cades</div>\n        <div class="timeline-text">Dez espias trazem relatório negativo; apenas Calebe e Josué confiam em Deus. A incredulidade da congregação provoca o decreto divino: a geração adulta morrerá no deserto em quarenta anos. Nova intercessão de Moisés (Nm 14.13–19) apela ao caráter de Deus (Êx 34.6–7).</div>',
     '<div class="timeline-period">Numbers 13–14</div>\n        <div class="timeline-title">The Twelve Spies — The Crisis at Kadesh</div>\n        <div class="timeline-text">Ten spies bring a negative report; only Caleb and Joshua trust God. The congregation\'s unbelief triggers the divine decree: the adult generation will die in the wilderness over forty years. A new intercession by Moses (Num 14:13–19) appeals to God\'s character (Exod 34:6–7).</div>'),
    ('<div class="timeline-period">Números 16–17</div>\n        <div class="timeline-title">Rebelião de Coré, Datã e Abirão</div>\n        <div class="timeline-text">Rebelião sacerdotal e civil contra Moisés e Arão. A terra abre e engole os rebeldes; fogo consome os 250 oferentes de incenso. A vara de Arão que floresceu confirma o sacerdócio levítico. Hebreus 5 aplica esta tipologia ao sacerdócio de Cristo.</div>',
     '<div class="timeline-period">Numbers 16–17</div>\n        <div class="timeline-title">The Rebellion of Korah, Dathan, and Abiram</div>\n        <div class="timeline-text">Priestly and civil rebellion against Moses and Aaron. The earth opens and swallows the rebels; fire consumes the 250 incense-offering leaders. Aaron\'s staff that budded confirms the Levitical priesthood. Hebrews 5 applies this typology to Christ\'s priesthood.</div>'),
    ('<div class="timeline-period">Números 20</div>\n        <div class="timeline-title">O Pecado de Moisés em Meriba — Por Que Ele Não Entrou em Canaã</div>\n        <div class="timeline-text">Deus ordena falar à rocha para produzir água. Moisés, irritado, golpeia a rocha duas vezes dizendo "ouvi-nos, rebeldes!" — arrogando a si e a Arão o crédito do milagre ("nós vos daremos água"). O julgamento: Moisés não entrará em Canaã. Paulo (1Co 10.4) afirma que a rocha era Cristo.</div>',
     '<div class="timeline-period">Numbers 20</div>\n        <div class="timeline-title">Moses\'s Sin at Meribah — Why He Did Not Enter Canaan</div>\n        <div class="timeline-text">God commands speaking to the rock to produce water. Moses, angry, strikes the rock twice saying "Hear now, you rebels!" — arrogating to himself and Aaron the credit for the miracle ("shall we bring water for you?"). The judgment: Moses will not enter Canaan. Paul (1 Cor 10:4) states that the rock was Christ.</div>'),
    (
        '<h2>Por Que Moisés Não Entrou na Terra Prometida — Análise Completa</h2>',
        '<h2>Why Moses Did Not Enter the Promised Land — Complete Analysis</h2>'
    ),
    (
        '<span class="callout-type">Passagem Central</span>\n      <p><strong>Números 20.1–13</strong> é o texto primário do pecado. O decreto de exclusão é confirmado em <strong>Números 20.12; 27.12–14</strong> e reiterado por Moisés em primeira pessoa em <strong>Deuteronômio 1.37; 3.23–28; 4.21–22; 32.48–52</strong>. A morte é narrada em <strong>Deuteronômio 34.1–8</strong>. Cada uma dessas passagens acrescenta uma camada diferente de perspectiva — exegética, teológica e pessoal.</p>',
        '<span class="callout-type">Central Passage</span>\n      <p><strong>Numbers 20:1–13</strong> is the primary text of the sin. The exclusion decree is confirmed in <strong>Numbers 20:12; 27:12–14</strong> and reiterated by Moses in the first person in <strong>Deuteronomy 1:37; 3:23–28; 4:21–22; 32:48–52</strong>. The death is narrated in <strong>Deuteronomy 34:1–8</strong>. Each of these passages adds a different layer of perspective — exegetical, theological, and personal.</p>'
    ),
    (
        '<h3>O Contexto Imediato — Números 20.1–13</h3>\n    <p>A cena ocorre em <strong>Cades</strong>, no deserto de Zim, no primeiro mês do quadragésimo ano da peregrinação (cf. Nm 33.38). O povo chegara ao mesmo lugar onde trinta e oito anos antes havia falhado com os espias — e agora murmura outra vez pela falta de água. Miriã havia morrido naquele mesmo lugar (Nm 20.1) — talvez contribuindo para o estado emocional de Moisés.</p>\n    <p>Deus ordena a Moisés com clareza: <em>"Toma a vara, e reúne a congregação, tu e Arão, teu irmão, e falai à rocha diante dos olhos deles, e ela dará a sua água"</em> (Nm 20.8). O comando é triplo e explícito: (1) toma a vara; (2) reúne o povo; (3) <strong>fala</strong> à rocha.</p>',
        '<h3>The Immediate Context — Numbers 20:1–13</h3>\n    <p>The scene takes place at <strong>Kadesh</strong>, in the wilderness of Zin, in the first month of the fortieth year of wandering (cf. Num 33:38). The people had arrived at the same place where thirty-eight years earlier they had failed with the spies — and now they grumble again for lack of water. Miriam had died in that same place (Num 20:1) — perhaps contributing to Moses\'s emotional state.</p>\n    <p>God commands Moses clearly: <em>"Take the staff, and assemble the congregation, you and Aaron your brother, and tell the rock before their eyes to yield its water"</em> (Num 20:8). The command is threefold and explicit: (1) take the staff; (2) assemble the people; (3) <strong>speak</strong> to the rock.</p>'
    ),
    (
        '<h3>O Que Moisés Fez de Errado — Uma Análise Precisa</h3>\n    <p>O texto de Números 20.10–11 registra exatamente o que aconteceu:</p>',
        '<h3>What Moses Did Wrong — A Precise Analysis</h3>\n    <p>The text of Numbers 20:10–11 records exactly what happened:</p>'
    ),
    (
        '"Moisés e Arão reuniram a assembleia diante da rocha; e ele lhes disse: Ouçam agora, rebeldes! Tiraremos água desta rocha para vocês? Então Moisés levantou a mão e feriu a rocha com a vara duas vezes; saiu muita água, e a assembleia e o seu gado beberam."\n      <span class="scripture-ref">Números 20.10–11 — NAA</span>',
        '"Moses and Aaron gathered the assembly together before the rock, and he said to them, \'Hear now, you rebels: shall we bring water for you out of this rock?\' And Moses lifted up his hand and struck the rock with his staff twice, and water came out abundantly, and the congregation and their livestock drank."\n      <span class="scripture-ref">Numbers 20:10–11 — ESV</span>'
    ),
    ('O texto identifica pelo menos <strong>quatro transgressões distintas</strong> nessa ação:', 'The text identifies at least <strong>four distinct transgressions</strong> in this action:'),
    ('<div class="timeline-period">Transgressão 1</div>\n        <div class="timeline-title">Golpeou em vez de Falar</div>\n        <div class="timeline-text">Deus mandou <em>falar</em> à rocha. Moisés <em>golpeou</em> com a vara — não uma, mas duas vezes. O golpe repetido sugere que na primeira vez a água não saiu, e Moisés bateu novamente com irritação crescente. Falar à rocha seria um ato de fé simples, dependente da palavra de Deus. Golpear era substituir a palavra pelo esforço físico — substituir a fé pelo método.</div>',
     '<div class="timeline-period">Transgression 1</div>\n        <div class="timeline-title">Struck Instead of Speaking</div>\n        <div class="timeline-text">God commanded Moses to <em>speak</em> to the rock. Moses <em>struck</em> it with the staff — not once, but twice. The repeated blow suggests that on the first strike the water did not come, and Moses struck again with growing irritation. Speaking to the rock would have been a simple act of faith, dependent on God\'s word. Striking it replaced the word with physical effort — replacing faith with method.</div>'),
    ('<div class="timeline-period">Transgressão 2</div>\n        <div class="timeline-title">Arrogou a Glória Divina</div>\n        <div class="timeline-text">"Acaso <strong>nós</strong> tiraremos água desta rocha para vós?" O pronome "nós" é devastador. Moisés e Arão colocaram-se como agentes do milagre — não como canais da ação divina. Quando Deus age por meio de um instrumento, o instrumento não pode reivindicar a autoria. A santificação de Deus diante do povo (Nm 20.12: "não me santificastes diante dos filhos de Israel") exige que a glória do milagre seja creditada ao único que pode produzi-la.</div>',
     '<div class="timeline-period">Transgression 2</div>\n        <div class="timeline-title">Arrogated Divine Glory</div>\n        <div class="timeline-text">"Shall <strong>we</strong> bring water for you out of this rock?" The pronoun "we" is devastating. Moses and Aaron placed themselves as agents of the miracle — not as channels of divine action. When God acts through an instrument, the instrument cannot claim authorship. The sanctification of God before the people (Num 20:12: "you did not believe in me, to uphold me as holy") requires that the glory of the miracle be credited to the only One who can produce it.</div>'),
    ('<div class="timeline-period">Transgressão 3</div>\n        <div class="timeline-title">Chamou o Povo de Rebeldes com Ira</div>\n        <div class="timeline-text">"Ouvi-me agora, <strong>rebeldes</strong>!" A palavra hebraica é <em>morim</em> (מֹרִים) — rebeldes, recalcitrantes. Embora o povo de fato estivesse murmurando, Moisés expressou essa palavra com raiva pessoal, não com a serena autoridade do mensageiro divino. O líder havia perdido o controle emocional — o homem que o texto descreve como "mui manso, mais do que todos os homens que havia sobre a face da terra" (Nm 12.3) agora explodia de fúria diante do povo.</div>',
     '<div class="timeline-period">Transgression 3</div>\n        <div class="timeline-title">Called the People Rebels in Anger</div>\n        <div class="timeline-text">"Hear now, you <strong>rebels</strong>!" The Hebrew word is <em>morim</em> (מֹרִים) — rebels, recalcitrant ones. Although the people were indeed grumbling, Moses expressed this word with personal anger, not with the calm authority of a divine messenger. The leader had lost emotional control — the man the text describes as "very meek, more than all people who were on the face of the earth" (Num 12:3) now erupted in fury before the people.</div>'),
    ('<div class="timeline-period">Transgressão 4</div>\n        <div class="timeline-title">Incredulidade — A Acusação Mais Profunda</div>\n        <div class="timeline-text">Números 20.12 diz: <em>"Porquanto não crastes em mim."</em> Esta é a acusação mais surpreendente — como pode Moisés, que falou com Deus "face a face", ser acusado de incredulidade? Deuteronômio 32.51 esclarece: "porque transgrediram contra mim... porque não me santificastes no meio dos filhos de Israel." A incredulidade de Moisés não era doutrinária — era funcional. No momento crítico, ele não confiou que a palavra de Deus fosse suficiente. Precisou <em>fazer algo</em> além do que Deus havia ordenado.</div>',
     '<div class="timeline-period">Transgression 4</div>\n        <div class="timeline-title">Unbelief — The Deepest Accusation</div>\n        <div class="timeline-text">Numbers 20:12 says: <em>"Because you did not believe in me."</em> This is the most surprising accusation — how can Moses, who spoke with God "face to face," be accused of unbelief? Deuteronomy 32:51 clarifies: "because you broke faith with me... because you did not treat me as holy in the midst of the people of Israel." Moses\'s unbelief was not doctrinal — it was functional. At the critical moment, he did not trust that God\'s word was sufficient. He needed to <em>do something</em> beyond what God had commanded.</div>'),
    (
        '<span class="callout-type">A Tipologia da Rocha — 1 Coríntios 10.4</span>\n      <p>Paulo declara que "a rocha era Cristo" (1Co 10.4). Na primeira vez que a rocha foi golpeada (Êx 17.6), o comando era correto: a rocha deveria ser ferida. Isso tipificava a crucificação — Cristo seria golpeado uma vez, definitivamente, para produzir as águas vivas da salvação. Na segunda vez (Nm 20), a rocha deveria ser <em>falada</em> — não golpeada novamente. Golpear a rocha duas vezes desfazia a tipologia: sugeria que o sacrifício de Cristo precisaria ser repetido. Hebreus 9.28 responde: "Cristo foi oferecido uma vez para tirar os pecados de muitos." O erro litúrgico de Moisés era um erro tipológico de consequências eternas.</p>',
        '<span class="callout-type">The Typology of the Rock — 1 Corinthians 10:4</span>\n      <p>Paul declares that "the rock was Christ" (1 Cor 10:4). The first time the rock was struck (Exod 17:6), the command was correct: the rock was to be struck. This typified the crucifixion — Christ would be struck once, definitively, to produce the living waters of salvation. The second time (Num 20), the rock was to be <em>spoken to</em> — not struck again. Striking the rock a second time broke the typology: it suggested that Christ\'s sacrifice would need to be repeated. Hebrews 9:28 answers: "Christ, having been offered once to bear the sins of many." Moses\'s liturgical error was a typological error with eternal consequences.</p>'
    ),
    (
        '<h3>O Veredicto Divino — Números 20.12</h3>',
        '<h3>The Divine Verdict — Numbers 20:12</h3>'
    ),
    (
        '"O <span style="font-variant:small-caps">Senhor</span> disse a Moisés e a Arão: Porque vocês não confiaram em mim, para santificar-me diante dos israelitas, vocês não introduzirão esta assembleia na terra que lhes darei."\n      <span class="scripture-ref">Números 20.12 — NAA</span>',
        '"And the <span style="font-variant:small-caps">Lord</span> said to Moses and Aaron, \'Because you did not believe in me, to uphold me as holy in the eyes of the people of Israel, therefore you shall not bring this assembly into the land that I have given them.\'"\n      <span class="scripture-ref">Numbers 20:12 — ESV</span>'
    ),
    (
        'A sentença tem dois elementos: <strong>diagnóstico</strong> ("não crastes em mim, para me santificardes") e <strong>consequência</strong> ("não introduzireis esta congregação na terra"). Note que a consequência recai sobre ambos — Moisés <em>e</em> Arão. Arão morreu no Monte Hor pouco depois (Nm 20.22–29), igualmente excluído de Canaã.',
        'The sentence has two elements: <strong>diagnosis</strong> ("you did not believe in me, to uphold me as holy") and <strong>consequence</strong> ("you shall not bring this assembly into the land"). Note that the consequence falls on both — Moses <em>and</em> Aaron. Aaron died on Mount Hor shortly after (Num 20:22–29), equally excluded from Canaan.'
    ),
    (
        '<h3>Moisés Tenta Reverter a Sentença — Deuteronômio 3.23–28</h3>\n    <p>Em Deuteronômio 3, Moisés relata em primeira pessoa sua tentativa de apelar da sentença. Este é um dos momentos mais comoventes de toda a Bíblia:</p>',
        '<h3>Moses Tries to Reverse the Sentence — Deuteronomy 3:23–28</h3>\n    <p>In Deuteronomy 3, Moses recounts in the first person his attempt to appeal the sentence. This is one of the most moving moments in all of Scripture:</p>'
    ),
    (
        '"Naquele tempo supliquei ao <span style="font-variant:small-caps">Senhor</span>, dizendo: Senhor <span style="font-variant:small-caps">Deus</span>, você começou a mostrar ao seu servo a sua grandeza e a sua poderosa mão... Deixe-me passar e ver aquela boa terra que está além do Jordão, aquela bela região montanhosa e o Líbano. Mas o <span style="font-variant:small-caps">Senhor</span> estava irado comigo por causa de vocês e não me atendeu. O <span style="font-variant:small-caps">Senhor</span> me disse: Basta! Não me fale mais sobre este assunto."\n      <span class="scripture-ref">Deuteronômio 3.23–26 — NAA</span>',
        '"And I pleaded with the <span style="font-variant:small-caps">Lord</span> at that time, saying, \'O Lord God, you have only begun to show your servant your greatness and your mighty hand... Please let me go over and see the good land beyond the Jordan, that good hill country and Lebanon.\' But the <span style="font-variant:small-caps">Lord</span> was angry with me because of you and would not listen to me. And the <span style="font-variant:small-caps">Lord</span> said to me, \'Enough from you; do not speak to me of this matter again.\'"\n      <span class="scripture-ref">Deuteronomy 3:23–26 — ESV</span>'
    ),
    (
        'A expressão <em>"Basta"</em> (hebraico: <em>rav-lekha</em>, רַב-לְךָ — "suficiente para ti") é a resposta mais sóbria imaginável. Deus não debate, não negocia, não oferece condições. A porta está fechada. Moisés então recebe uma consolação parcial: poderá ver a terra do alto do monte Pisga, em todas as direções — mas não a cruzará (Dt 3.27).',
        'The expression <em>"Enough"</em> (Hebrew: <em>rav-lekha</em>, רַב-לְךָ — "it is enough for you") is the most sober response imaginable. God does not debate, negotiate, or offer conditions. The door is closed. Moses then receives a partial consolation: he will be able to see the land from the top of Mount Pisgah, in all directions — but he will not cross it (Deut 3:27).'
    ),
    (
        '<h3>Moisés Atribui Sua Exclusão ao Povo — Uma Perspectiva Complexa</h3>\n    <p>Em três passagens do Deuteronômio (1.37; 3.26; 4.21), Moisés afirma que foi excluído de Canaã <em>"por causa de vós"</em> — por causa do povo. Isso parece contradizer Números 20, que aponta o pecado do próprio Moisés. Como reconciliar?</p>',
        '<h3>Moses Attributes His Exclusion to the People — A Complex Perspective</h3>\n    <p>In three passages in Deuteronomy (1:37; 3:26; 4:21), Moses states that he was excluded from Canaan <em>"because of you"</em> — because of the people. This seems to contradict Numbers 20, which points to Moses\'s own sin. How to reconcile?</p>'
    ),
    (
        '<div class="card-title">Não há contradição — há camadas</div>\n        <p>O povo provocou a situação com suas murmurações (Nm 20.3–5). Sem a provocação do povo, Moisés não teria chegado àquele momento de pressão extrema. Há, portanto, um sentido legítimo em que o povo foi a causa ocasional do pecado de Moisés. Mas Moisés permanece responsável pela sua reação. A culpa não é transferida — ela é compartilhada em camadas distintas.</p>',
        '<div class="card-title">No contradiction — there are layers</div>\n        <p>The people provoked the situation with their grumbling (Num 20:3–5). Without the people\'s provocation, Moses would not have arrived at that moment of extreme pressure. There is, therefore, a legitimate sense in which the people were the occasional cause of Moses\'s sin. But Moses remains responsible for his reaction. The guilt is not transferred — it is shared in distinct layers.</p>'
    ),
    (
        '<div class="card-title">A Dor Pessoal de Moisés</div>\n        <p>Deuteronômio 3.25 revela que Moisés genuinamente desejava entrar em Canaã. Não era indiferença — era uma perda profunda. O homem que passou quarenta anos conduzindo Israel em direção à Terra Prometida morreria no limiar, vendo-a de longe mas nunca pisando nela. A exclusão de Moisés é uma das cenas mais patéticas e comoventes da história bíblica.</p>',
        '<div class="card-title">Moses\'s Personal Grief</div>\n        <p>Deuteronomy 3:25 reveals that Moses genuinely desired to enter Canaan. It was not indifference — it was a deep loss. The man who spent forty years leading Israel toward the Promised Land would die at the threshold, seeing it from afar but never setting foot in it. Moses\'s exclusion is one of the most poignant and moving scenes in biblical history.</p>'
    ),
    (
        '<h3>A Vista do Monte Nebo — Deuteronômio 34.1–4</h3>\n    <p>Deus concede a Moisés uma visão panorâmica antes da morte. Do topo do Monte Nebo (Pisgá), Moisés pode ver:</p>',
        '<h3>The View from Mount Nebo — Deuteronomy 34:1–4</h3>\n    <p>God grants Moses a panoramic view before his death. From the top of Mount Nebo (Pisgah), Moses can see:</p>'
    ),
    (
        '<span class="name-tag">Gileade até Dã (norte)</span>\n      <span class="name-tag">Toda Naftali</span>\n      <span class="name-tag">Terra de Efraim e Manassés</span>\n      <span class="name-tag">Toda a terra de Judá até o Mar Ocidental (Mediterrâneo)</span>\n      <span class="name-tag">O Neguebe (sul)</span>\n      <span class="name-tag">O vale de Jericó, a Cidade das Palmeiras, até Zoar</span>',
        '<span class="name-tag">Gilead as far as Dan (north)</span>\n      <span class="name-tag">All of Naphtali</span>\n      <span class="name-tag">Land of Ephraim and Manasseh</span>\n      <span class="name-tag">All the land of Judah as far as the Western Sea (Mediterranean)</span>\n      <span class="name-tag">The Negev (south)</span>\n      <span class="name-tag">The Valley of Jericho, the City of Palm Trees, as far as Zoar</span>'
    ),
    (
        'Deus confirma: <em>"Esta é a terra que jurei dar a Abraão, a Isaque e a Jacó"</em> (Dt 34.4). A promessa patriarcal está sendo cumprida — Moisés a vê com seus próprios olhos. A consolação é real, mas a exclusão também. A graça e a justiça se tocam no mesmo momento, no mesmo monte.',
        'God confirms: <em>"This is the land of which I swore to Abraham, to Isaac, and to Jacob"</em> (Deut 34:4). The patriarchal promise is being fulfilled — Moses sees it with his own eyes. The consolation is real, but so is the exclusion. Grace and justice meet at the same moment, on the same mountain.'
    ),
    (
        '<span class="callout-type">Significado Teológico da Exclusão</span>\n      <p>A exclusão de Moisés de Canaã é, na hermenêutica reformada, parte do argumento tipológico do AT: a Lei (representada por Moisés) pode conduzir Israel até a fronteira da herança, mas não pode levá-la a entrar. Somente <strong>Josué</strong> — cujo nome em hebraico é <em>Yehoshua</em> (יְהוֹשֻׁעַ), a mesma raiz que <em>Yeshua</em> (Jesus) — conduziu o povo à terra. Paulo desenvolve essa lógica em Gálatas 3.23–25: "a lei nos serviu de aio para nos conduzir a Cristo." A lei guia até Cristo, mas não pode substituí-lo. Moisés morre na fronteira; Jesus entra.</p>',
        '<span class="callout-type">Theological Significance of the Exclusion</span>\n      <p>Moses\'s exclusion from Canaan is, in Reformed hermeneutics, part of the OT typological argument: the Law (represented by Moses) can lead Israel to the boundary of the inheritance, but cannot bring it in. Only <strong>Joshua</strong> — whose name in Hebrew is <em>Yehoshua</em> (יְהוֹשֻׁעַ), the same root as <em>Yeshua</em> (Jesus) — led the people into the land. Paul develops this logic in Galatians 3:23–25: "the law was our guardian until Christ came." The law guides to Christ, but cannot replace him. Moses dies at the border; Jesus enters.</p>'
    ),
    (
        '<h2>A Serpente de Bronze — João 3.14</h2>\n    <p>Em Números 21, cobras ardentes atacam o povo após nova murmuração. Deus ordena Moisés a fazer uma serpente de bronze e erguê-la num poste — quem olhasse para ela, viveria. Jesus usa este evento como tipologia direta de sua própria crucificação (Jo 3.14–15): "E como Moisés levantou a serpente no deserto, assim importa que o Filho do Homem seja levantado, para que todo aquele que nele crê tenha a vida eterna."</p>',
        '<h2>The Bronze Serpent — John 3:14</h2>\n    <p>In Numbers 21, fiery serpents attack the people after another episode of grumbling. God commands Moses to make a bronze serpent and lift it up on a pole — whoever looked at it would live. Jesus uses this event as a direct typology of his own crucifixion (John 3:14–15): "And as Moses lifted up the serpent in the wilderness, so must the Son of Man be lifted up, that whoever believes in him may have eternal life."</p>'
    ),
    (
        '<h2>Deuteronômio — O Sermão do Adeus</h2>\n    <p>Deuteronômio (grego: "segunda lei") é o discurso final de Moisés nas planícies de Moabe, endereçado à nova geração. É uma renovação da aliança — não uma nova lei, mas a lei reafirmada e aplicada à nova situação. Seu coração é o <em>Shemá</em> (Dt 6.4–9): <em>"Ouve, Israel: O SENHOR nosso Deus é o único SENHOR."</em></p>',
        '<h2>Deuteronomy — The Farewell Sermon</h2>\n    <p>Deuteronomy (Greek: "second law") is Moses\'s final discourse on the plains of Moab, addressed to the new generation. It is a covenant renewal — not a new law, but the law reaffirmed and applied to the new situation. Its heart is the <em>Shema</em> (Deut 6:4–9): <em>"Hear, O Israel: The Lord our God, the Lord is one."</em></p>'
    ),
    (
        '<h2>A Morte de Moisés — Deuteronômio 34</h2>\n    <p>Moisés sobe ao Monte Nebo (Pisgá), contempla toda a terra prometida — do Neguebe ao Hermom — e morre. Sua morte é narrada com sobriedade e mistério:</p>',
        '<h2>The Death of Moses — Deuteronomy 34</h2>\n    <p>Moses ascends Mount Nebo (Pisgah), surveys all the promised land — from the Negev to Hermon — and dies. His death is narrated with sobriety and mystery:</p>'
    ),
    (
        '<div class="card-title">Morreu com 120 anos</div>\n        <p>"Seus olhos não se tinham escurecido, nem perdera o viço" (Dt 34.7). A plenitude vital de Moisés até o fim contrasta com o destino ordinário da velhice — sinal da graça divina sobre seu servo.</p>',
        '<div class="card-title">Died at 120 years old</div>\n        <p>"His eye was undimmed, and his vigor unabated" (Deut 34:7). Moses\'s full vitality to the end contrasts with the ordinary fate of old age — a sign of divine grace upon his servant.</p>'
    ),
    (
        '<div class="card-title">Sepultura Misteriosa</div>\n        <p>O SENHOR o sepultou num vale em Moabe, "e ninguém sabe onde fica o seu sepulcro até hoje" (Dt 34.6). Judas 9 revela que Miguel, o arcanjo, disputou com o diabo pelo corpo de Moisés — passagem enigmática relacionada à sua aparição na Transfiguração.</p>',
        '<div class="card-title">Mysterious Burial</div>\n        <p>The Lord buried him in a valley in Moab, "but no one knows the place of his burial to this day" (Deut 34:6). Jude 9 reveals that Michael the archangel disputed with the devil over the body of Moses — an enigmatic passage related to his appearance at the Transfiguration.</p>'
    ),
    # teologia
    (
        '<span class="section-tag">Teologia Sistemática</span>\n      <h1 class="section-title">A Teologia de Moisés</h1>\n      <p class="section-lead">As grandes contribuições teológicas do ministério mosaico ao cânone das Escrituras.</p>',
        '<span class="section-tag">Systematic Theology</span>\n      <h1 class="section-title">The Theology of Moses</h1>\n      <p class="section-lead">The major theological contributions of the Mosaic ministry to the biblical canon.</p>'
    ),
    (
        '<h2>1. Monoteísmo Radical</h2>\n    <p>O ministério de Moisés estabelece o monoteísmo exclusivo de Israel em contraste frontal com o politeísmo egípcio e cananeu. O Shemá (Dt 6.4) é a declaração mais clara: <em>"YHWH Elohenu YHWH Echad"</em> — YHWH é nosso Deus, YHWH é único. Não apenas que Israel deve adorar somente a YHWH (henoteísmo prático), mas que somente YHWH existe como Deus verdadeiro.</p>',
        '<h2>1. Radical Monotheism</h2>\n    <p>Moses\'s ministry establishes Israel\'s exclusive monotheism in direct contrast to Egyptian and Canaanite polytheism. The Shema (Deut 6:4) is the clearest declaration: <em>"YHWH Elohenu YHWH Echad"</em> — the Lord is our God, the Lord is one. Not merely that Israel must worship only YHWH (practical henotheism), but that only YHWH exists as the true God.</p>'
    ),
    (
        '<h2>2. Revelação do Nome Divino</h2>\n    <p>A revelação do Nome YHWH em Êxodo 3.14–15 e 6.2–3 é o evento epistemológico central do Pentateuco. O Nome não é apenas uma designação — é uma autodivulgação do caráter e ser de Deus. Êxodo 34.6–7 é a "definição" divina de si mesmo, e toda a teologia bíblica posterior é uma expansão desse núcleo.</p>',
        '<h2>2. Revelation of the Divine Name</h2>\n    <p>The revelation of the Name YHWH in Exodus 3:14–15 and 6:2–3 is the central epistemological event of the Pentateuch. The Name is not merely a designation — it is a self-disclosure of God\'s character and being. Exodus 34:6–7 is God\'s divine "definition" of himself, and all subsequent biblical theology is an expansion of this core.</p>'
    ),
    (
        '<h2>3. Teologia da Aliança</h2>\n    <p>Moisés é o mediador da aliança mais elaborada do AT. A Aliança Mosaica (também chamada Aliança Sinaítica ou Mosaica) tem estrutura tripartida: <strong>YHWH como Rei</strong>, <strong>Israel como povo da aliança</strong> e <strong>a Lei como constituição</strong>. Ela pressupõe e amplia as alianças abraâmica e noáica, e é cumprida e superada pela Nova Aliança em Cristo (Jr 31.31–34; Hb 8).</p>',
        '<h2>3. Covenant Theology</h2>\n    <p>Moses is the mediator of the most elaborate covenant in the OT. The Mosaic Covenant (also called the Sinaitic or Mosaic Covenant) has a tripartite structure: <strong>YHWH as King</strong>, <strong>Israel as covenant people</strong>, and <strong>the Law as constitution</strong>. It presupposes and amplifies the Abrahamic and Noahic covenants, and is fulfilled and surpassed by the New Covenant in Christ (Jer 31:31–34; Heb 8).</p>'
    ),
    (
        '<h2>4. Tipologia Sacerdotal</h2>\n    <p>O sistema levítico e o tabernáculo instituídos por Moisés formam um sistema tipológico completo que aponta para Cristo. Hebreus 8–10 desenvolve esta tipologia com detalhe: Cristo é o Sumo Sacerdote superior (Hb 4.14), o templo verdadeiro (Jo 2.21), o sacrifício definitivo (Hb 9.26), e o mediador da Nova Aliança (Hb 9.15).</p>',
        '<h2>4. Priestly Typology</h2>\n    <p>The Levitical system and tabernacle instituted by Moses form a complete typological system pointing to Christ. Hebrews 8–10 develops this typology in detail: Christ is the superior High Priest (Heb 4:14), the true temple (John 2:21), the definitive sacrifice (Heb 9:26), and the mediator of the New Covenant (Heb 9:15).</p>'
    ),
    (
        '<span class="callout-type">Perspectiva Reformada-Calvinista</span>\n      <p>Na teologia da aliança reformada (Calvino, Westminster), a Lei Mosaica tem três usos: <strong>usus civilis</strong> (refrear o mal na sociedade), <strong>usus elenchticus</strong> (revelar o pecado e conduzir a Cristo — Gl 3.24) e <strong>usus didacticus / normativus</strong> (guia para a vida do crente regenerado). Os dez mandamentos permanecem como lei moral vinculante — não como caminho de salvação, mas como norma de vida nova.</p>',
        '<span class="callout-type">Reformed-Calvinist Perspective</span>\n      <p>In Reformed covenant theology (Calvin, Westminster), the Mosaic Law has three uses: <strong>usus civilis</strong> (restraining evil in society), <strong>usus elenchticus</strong> (revealing sin and driving to Christ — Gal 3:24), and <strong>usus didacticus / normativus</strong> (guide for the life of the regenerate believer). The ten commandments remain as binding moral law — not as a path of salvation, but as the norm of new life.</p>'
    ),
    (
        '<h2>5. A Esperança Escatológica</h2>\n    <p>Deuteronômio 18.15–18 é a promessa messiânica central de Moisés: Deus levantará um profeta <em>"semelhante a mim"</em> — que falará as palavras divinas. Pedro (At 3.22) e Estêvão (At 7.37) identificam explicitamente este profeta com Jesus. A grandeza de Moisés cria a categoria que somente o Filho de Deus poderia preencher.</p>',
        '<h2>5. Eschatological Hope</h2>\n    <p>Deuteronomy 18:15–18 is the central messianic promise of Moses: God will raise up a prophet <em>"like me"</em> — who will speak the divine words. Peter (Acts 3:22) and Stephen (Acts 7:37) explicitly identify this prophet with Jesus. The greatness of Moses creates the category that only the Son of God could fill.</p>'
    ),
    (
        '<h2>6. O Papel de Moisés na Teologia Bíblico-Sistemática</h2>',
        '<h2>6. Moses\'s Role in Biblical-Systematic Theology</h2>'
    ),
    (
        '<div class="card-title">Hermenêutica Cristológica</div>\n        <p>Jesus afirma em João 5.46: <em>"Se crêsseis em Moisés, creríeis em mim, porque ele escreveu de mim."</em> Lucas 24.27 registra que Cristo expôs "em todas as Escrituras as coisas que a ele se referiam, começando por Moisés." Ler Moisés corretamente é ler Cristo.</p>',
        '<div class="card-title">Christological Hermeneutics</div>\n        <p>Jesus states in John 5:46: <em>"If you believed Moses, you would believe me; for he wrote of me."</em> Luke 24:27 records that Christ expounded "in all the Scriptures the things concerning himself, beginning with Moses." To read Moses correctly is to read Christ.</p>'
    ),
    (
        '<div class="card-title">Autoridade do Pentateuco</div>\n        <p>A autoria mosaica do Pentateuco é assumida consistentemente pelo NT (Mc 7.10; Jo 1.17; 7.19; At 3.22; Rm 10.5). Embora a crítica liberal (Wellhausen, JEPD) questione isso, a confirmação do próprio Cristo (Jo 5.45–47) é o argumento decisivo para a hermenêutica evangélica.</p>',
        '<div class="card-title">Authority of the Pentateuch</div>\n        <p>Mosaic authorship of the Pentateuch is consistently assumed by the NT (Mark 7:10; John 1:17; 7:19; Acts 3:22; Rom 10:5). Although liberal criticism (Wellhausen, JEPD) questions this, Christ\'s own confirmation (John 5:45–47) is the decisive argument for evangelical hermeneutics.</p>'
    ),
    # nt section
    (
        '<span class="section-tag">Cristologia e Novo Testamento</span>\n      <h1 class="section-title">Moisés no NT e os Tipos de Cristo</h1>\n      <p class="section-lead">Como o maior profeta de Israel aponta para Aquele que é maior que Moisés.</p>',
        '<span class="section-tag">Christology and New Testament</span>\n      <h1 class="section-title">Moses in the NT and the Types of Christ</h1>\n      <p class="section-lead">How the greatest prophet of Israel points to the One who is greater than Moses.</p>'
    ),
    (
        '<h2>Cristo, o Profeta Semelhante a Moisés</h2>\n    <p>Deuteronômio 18.15 é cumprido em Cristo de maneira plena. O paralelo é extenso e preciso:</p>',
        '<h2>Christ, the Prophet Like Moses</h2>\n    <p>Deuteronomy 18:15 is fulfilled in Christ in a complete way. The parallel is extensive and precise:</p>'
    ),
    ('<th>Aspecto</th>\n          <th>Moisés</th>\n          <th>Cristo — Cumprimento</th>', '<th>Aspect</th>\n          <th>Moses</th>\n          <th>Christ — Fulfillment</th>'),
    ('<td>Ameaça na infância</td>\n          <td>Decreto de morte pelo Faraó (Êx 1)</td>\n          <td>Decreto de morte por Herodes (Mt 2)</td>', '<td>Childhood threat</td>\n          <td>Death decree by Pharaoh (Exod 1)</td>\n          <td>Death decree by Herod (Matt 2)</td>'),
    ('<td>Saída do Egito</td>\n          <td>Éxodo de Israel (Êx 12–14)</td>\n          <td>"Do Egito chamei meu filho" (Mt 2.15; Os 11.1)</td>', '<td>Out of Egypt</td>\n          <td>Exodus of Israel (Exod 12–14)</td>\n          <td>"Out of Egypt I called my son" (Matt 2:15; Hos 11:1)</td>'),
    ('<td>Travessia das águas</td>\n          <td>Mar Vermelho (Êx 14)</td>\n          <td>Batismo no Jordão (Mt 3)</td>', '<td>Crossing through water</td>\n          <td>Red Sea (Exod 14)</td>\n          <td>Baptism in the Jordan (Matt 3)</td>'),
    ('<td>Quarenta dias/anos no deserto</td>\n          <td>40 anos de peregrinação</td>\n          <td>40 dias de tentação (Mt 4)</td>', '<td>Forty days/years in the desert</td>\n          <td>40 years of wandering</td>\n          <td>40 days of temptation (Matt 4)</td>'),
    ('<td>Revelação no monte</td>\n          <td>Sinai — dez mandamentos</td>\n          <td>Sermão do Monte — "mas eu vos digo" (Mt 5–7)</td>', '<td>Revelation on a mountain</td>\n          <td>Sinai — ten commandments</td>\n          <td>Sermon on the Mount — "but I say to you" (Matt 5–7)</td>'),
    ('<td>Mediador da Aliança</td>\n          <td>Aliança Sinaítica (Êx 24)</td>\n          <td>Nova Aliança no sangue (Lc 22.20; Hb 9.15)</td>', '<td>Mediator of the Covenant</td>\n          <td>Sinai Covenant (Exod 24)</td>\n          <td>New Covenant in his blood (Luke 22:20; Heb 9:15)</td>'),
    ('<td>Pão do Céu</td>\n          <td>Maná no deserto (Êx 16)</td>\n          <td>"Eu sou o pão da vida" (Jo 6.35, 48–51)</td>', '<td>Bread from Heaven</td>\n          <td>Manna in the wilderness (Exod 16)</td>\n          <td>"I am the bread of life" (John 6:35, 48–51)</td>'),
    ('<td>Água da rocha</td>\n          <td>Rocha em Horebe e Meriba</td>\n          <td>"A rocha era Cristo" (1Co 10.4)</td>', '<td>Water from the rock</td>\n          <td>Rock at Horeb and Meribah</td>\n          <td>"The rock was Christ" (1 Cor 10:4)</td>'),
    ('<td>Intercessão sacrificial</td>\n          <td>"Risca-me do teu livro" (Êx 32.32)</td>\n          <td>Expiação substitutiva real (2Co 5.21)</td>', '<td>Sacrificial intercession</td>\n          <td>"Blot me out of your book" (Exod 32:32)</td>\n          <td>Real substitutionary atonement (2 Cor 5:21)</td>'),
    (
        '<h2>A Transfiguração — Marcos 9.2–8</h2>\n    <p>Moisés aparece ao lado de Elias na Transfiguração — a Lei e os Profetas diante do próprio Cristo. Lucas 9.31 revela que eles falavam sobre o <em>êxodo</em> (<em>exodon</em>) de Jesus em Jerusalém — sua morte expiatória como o êxodo definitivo. A voz do Pai ordena: <em>"Este é o meu Filho amado; a ele ouvi."</em> — uma referência direta a Deuteronômio 18.15 ("a ele ouvireis").</p>',
        '<h2>The Transfiguration — Mark 9:2–8</h2>\n    <p>Moses appears alongside Elijah at the Transfiguration — the Law and the Prophets before Christ himself. Luke 9:31 reveals that they were speaking about the <em>exodus</em> (<em>exodon</em>) of Jesus in Jerusalem — his atoning death as the definitive Exodus. The Father\'s voice commands: <em>"This is my beloved Son; listen to him"</em> — a direct reference to Deuteronomy 18:15 ("you shall listen to him").</p>'
    ),
    (
        '<h2>Cristo Superior a Moisés — Hebreus 3.1–6</h2>\n    <p>Hebreus apresenta a comparação mais explícita: Moisés foi fiel como <strong>servo</strong> na casa de Deus (testemunhando o que viria); Cristo foi fiel como <strong>Filho</strong> sobre a casa de Deus. A honra de Cristo supera a de Moisés como o construtor supera a obra. O argumento é preciso: se Moisés merece tanta glória, quanto mais o Filho!</p>',
        '<h2>Christ Superior to Moses — Hebrews 3:1–6</h2>\n    <p>Hebrews presents the most explicit comparison: Moses was faithful as a <strong>servant</strong> in God\'s house (testifying to what was to come); Christ was faithful as a <strong>Son</strong> over God\'s house. Christ\'s honor surpasses Moses\'s as the builder surpasses the building. The argument is precise: if Moses deserves so much glory, how much more the Son!</p>'
    ),
    (
        '"Pois aquele que construiu a casa tem mais honra do que a própria casa... Moisés foi fiel em toda a casa de Deus como servo... mas Cristo é fiel como Filho sobre a própria casa de Deus."\n      <span class="scripture-ref">Hebreus 3.3–6 — NAA</span>',
        '"For Jesus has been counted worthy of more glory than Moses — as much more glory as the builder of a house has more honor than the house itself... Moses was faithful in all God\'s house as a servant... but Christ is faithful over God\'s house as a Son."\n      <span class="scripture-ref">Hebrews 3:3–6 — ESV</span>'
    ),
    (
        '<h2>A Nova Aliança Supera a Mosaica</h2>\n    <p>Hebreus 8 cita Jeremias 31.31–34 para demonstrar que a Aliança Mosaica era temporária e preparatória. O fato de Deus ter prometido uma <em>nova</em> aliança implica que a anterior era inadequada para realizar o propósito final — não pela fraqueza da Lei em si, mas pela fraqueza do povo (Hb 8.8). Cristo, o mediador da Nova Aliança, realiza o que a Lei apenas prometia: escreve a lei no coração, oferece perdão completo e proporciona o conhecimento direto de Deus.</p>',
        '<h2>The New Covenant Surpasses the Mosaic</h2>\n    <p>Hebrews 8 cites Jeremiah 31:31–34 to demonstrate that the Mosaic Covenant was temporary and preparatory. The fact that God promised a <em>new</em> covenant implies that the previous one was inadequate to achieve the final purpose — not because of weakness in the Law itself, but because of the weakness of the people (Heb 8:8). Christ, the mediator of the New Covenant, accomplishes what the Law only promised: writes the law on the heart, offers complete forgiveness, and provides direct knowledge of God.</p>'
    ),
    (
        '<h2>O Cântico de Moisés na Eternidade</h2>\n    <p>Apocalipse 15.3 descreve os remidos sobre o mar de vidro cantando "o cântico de Moisés, servo de Deus, e o cântico do Cordeiro." O Êxodo terreno encontra seu cumprimento no Êxodo celestial — o povo de Deus salvo das pragas do juízo final, glorificando o Deus que os libertou. A história de Moisés não termina no Monte Nebo — ela reverbera na eternidade.</p>',
        '<h2>The Song of Moses in Eternity</h2>\n    <p>Revelation 15:3 describes the redeemed on the sea of glass singing "the song of Moses, the servant of God, and the song of the Lamb." The earthly Exodus finds its fulfillment in the heavenly Exodus — the people of God saved from the plagues of final judgment, glorifying the God who delivered them. The story of Moses does not end at Mount Nebo — it reverberates in eternity.</p>'
    ),
    (
        '<span class="callout-type">Síntese Final</span>\n      <p>Moisés é o maior homem do Antigo Testamento — mas sua grandeza é precisamente sua função tipológica. Cada aspecto de seu ministério aponta além de si mesmo: seu nascimento aponta para a encarnação; sua libertação aponta para a redenção; sua mediação aponta para a intercessão de Cristo; sua lei aponta para o evangelho; sua morte aponta para o sacrifício; sua sepultura misteriosa aponta para a ressurreição. Ele não é o destino — é a seta que indica o destino. "A lei foi dada por Moisés; a graça e a verdade vieram por Jesus Cristo" (Jo 1.17).</p>',
        '<span class="callout-type">Final Synthesis</span>\n      <p>Moses is the greatest man of the Old Testament — but his greatness is precisely his typological function. Every aspect of his ministry points beyond itself: his birth points to the incarnation; his liberation points to redemption; his mediation points to Christ\'s intercession; his law points to the gospel; his death points to the sacrifice; his mysterious burial points to the resurrection. He is not the destination — he is the arrow that points to the destination. "The law was given through Moses; grace and truth came through Jesus Christ" (John 1:17).</p>'
    ),
    # pentateuco section
    (
        '<span class="section-tag">Autoria e Cânon</span>\n      <h1 class="section-title">Moisés e o Pentateuco</h1>\n      <p class="section-lead">Os cinco primeiros livros da Bíblia — escritos por Moisés, fundamento de toda a revelação subsequente.</p>',
        '<span class="section-tag">Authorship and Canon</span>\n      <h1 class="section-title">Moses and the Pentateuch</h1>\n      <p class="section-lead">The first five books of the Bible — written by Moses, the foundation of all subsequent revelation.</p>'
    ),
    (
        'O Pentateuco (do grego <em>pentateuchos</em> — "os cinco rolos") é a base de toda a Escritura. Os judeus o chamam de <strong>Torah</strong> (תּוֹרָה — "instrução, lei"), e os próprios livros afirmam ou implicam autoria mosaica em dezenas de passagens. Jesus, os apóstolos e os autores do NT confirmam essa autoria consistentemente.',
        'The Pentateuch (from the Greek <em>pentateuchos</em> — "the five scrolls") is the foundation of all Scripture. Jews call it the <strong>Torah</strong> (תּוֹרָה — "instruction, law"), and the books themselves affirm or imply Mosaic authorship in dozens of passages. Jesus, the apostles, and the NT authors confirm this authorship consistently.'
    ),
    (
        '<h2>A Autoria Mosaica — Base Bíblica</h2>',
        '<h2>Mosaic Authorship — Biblical Basis</h2>'
    ),
    (
        '<span class="callout-type">Confirmação do Próprio Cristo</span>\n      <p>Jesus é o testemunho mais forte da autoria mosaica: "Se crêsseis em Moisés, creríeis em mim, porque <strong>ele escreveu de mim</strong>" (Jo 5.46). Em Lucas 24.27, o Cristo ressurreto expõe as Escrituras "começando por Moisés." Em Marcos 7.10 atribui explicitamente o quinto mandamento a Moisés. A confirmação de Cristo não pode ser descartada sem comprometer a autoridade de Jesus como mestre.</p>',
        '<span class="callout-type">Confirmed by Christ Himself</span>\n      <p>Jesus is the strongest witness for Mosaic authorship: "If you believed Moses, you would believe me; for <strong>he wrote of me</strong>" (John 5:46). In Luke 24:27, the risen Christ expounds the Scriptures "beginning with Moses." In Mark 7:10 he explicitly attributes the fifth commandment to Moses. Christ\'s confirmation cannot be dismissed without compromising Jesus\'s authority as teacher.</p>'
    ),
    ('<tr><td>"Moisés escreveu estas palavras"</td><td>Autotestemunho interno</td><td>Êx 24.4; 34.27; Nm 33.2; Dt 31.9, 22, 24</td></tr>', '<tr><td>"Moses wrote these words"</td><td>Internal self-testimony</td><td>Exod 24:4; 34:27; Num 33:2; Deut 31:9, 22, 24</td></tr>'),
    ('<tr><td>"No livro de Moisés está escrito"</td><td>Josué</td><td>Js 8.31–32; 23.6</td></tr>', '<tr><td>"In the book of Moses it is written"</td><td>Joshua</td><td>Josh 8:31–32; 23:6</td></tr>'),
    ('<tr><td>"Como está escrito na lei de Moisés"</td><td>1 Reis / Neemias</td><td>1Rs 2.3; Ne 8.1; Dn 9.13</td></tr>', '<tr><td>"As it is written in the law of Moses"</td><td>1 Kings / Nehemiah</td><td>1 Kgs 2:3; Neh 8:1; Dan 9:13</td></tr>'),
    ('<tr><td>"Moisés escreveu de mim"</td><td>Jesus</td><td>Jo 5.46–47</td></tr>', '<tr><td>"Moses wrote of me"</td><td>Jesus</td><td>John 5:46–47</td></tr>'),
    ('<tr><td>"A lei foi dada por Moisés"</td><td>João</td><td>Jo 1.17</td></tr>', '<tr><td>"The law was given through Moses"</td><td>John</td><td>John 1:17</td></tr>'),
    ('<tr><td>"Moisés disse..." (citando Deuteronômio)</td><td>Paulo</td><td>Rm 10.5; 1Co 9.9</td></tr>', '<tr><td>"Moses said..." (citing Deuteronomy)</td><td>Paul</td><td>Rom 10:5; 1 Cor 9:9</td></tr>'),
    ('<tr><td>"No livro de Moisés" (citando Êxodo)</td><td>Marcos</td><td>Mc 12.26</td></tr>', '<tr><td>"In the book of Moses" (citing Exodus)</td><td>Mark</td><td>Mark 12:26</td></tr>'),
    (
        '<h2>A Crítica Liberal — JEPD e a Resposta Evangélica</h2>\n    <p>No século XIX, Julius Wellhausen desenvolveu a <strong>Hipótese Documentária</strong> (teoria JEPD), propondo que o Pentateuco é uma compilação de quatro fontes independentes: <em>Jahvista (J), Eloísta (E), Deuteronomista (D)</em> e <em>Sacerdotal (P)</em>, compostas entre os séculos X e V a.C. — muito depois de Moisés. Esta hipótese dominou a teologia liberal por mais de um século.</p>',
        '<h2>Liberal Criticism — JEDP and the Evangelical Response</h2>\n    <p>In the 19th century, Julius Wellhausen developed the <strong>Documentary Hypothesis</strong> (JEDP theory), proposing that the Pentateuch is a compilation of four independent sources: <em>Yahwist (J), Elohist (E), Deuteronomist (D)</em>, and <em>Priestly (P)</em>, composed between the 10th and 5th centuries BC — long after Moses. This hypothesis dominated liberal theology for over a century.</p>'
    ),
    (
        '<div class="card-title">Problemas com JEPD</div>\n        <p>• A alternância entre YHWH e Elohim (base da teoria) tem explicação literária interna<br>• Documentos hititas do 2º milênio a.C. confirmam o padrão de tratados de aliança de Êxodo<br>• Descobertas arqueológicas (Ebla, Ugarit, Mari) confirmam o contexto do 2º milênio<br>• A teoria não tem evidência manuscrita — nenhum fragmento J, E, D ou P jamais foi encontrado</p>',
        '<div class="card-title">Problems with JEDP</div>\n        <p>• The alternation between YHWH and Elohim (the theory\'s foundation) has an internal literary explanation<br>• Hittite documents from the 2nd millennium BC confirm the covenant treaty pattern of Exodus<br>• Archaeological discoveries (Ebla, Ugarit, Mari) confirm a 2nd millennium context<br>• The theory has no manuscript evidence — no fragment labeled J, E, D, or P has ever been found</p>'
    ),
    (
        '<div class="card-title">Posição Evangélica</div>\n        <p>A autoria mosaica é consistente com toda a evidência interna e com o testemunho do NT. Moisés era letrado (formado nas escolas egípcias), tinha acesso às tradições patriarcais orais e escritas, e viveu no século em que os eventos ocorreram. Isso não exclui a possibilidade de pequenas atualizações editoriais (ex: Dt 34, sobre a morte de Moisés — provavelmente de Josué).</p>',
        '<div class="card-title">Evangelical Position</div>\n        <p>Mosaic authorship is consistent with all internal evidence and the testimony of the NT. Moses was literate (trained in Egyptian scribal schools), had access to oral and written patriarchal traditions, and lived in the century when the events occurred. This does not exclude the possibility of minor editorial updates (e.g., Deut 34, about the death of Moses — probably by Joshua).</p>'
    ),
    (
        '<h2>Estrutura do Pentateuco como Unidade</h2>\n    <p>Os cinco livros formam uma narrativa progressiva com uma estrutura teológica coerente. Não são cinco documentos independentes — são cinco atos de uma única história:</p>',
        '<h2>The Pentateuch as a Unified Structure</h2>\n    <p>The five books form a progressive narrative with a coherent theological structure. They are not five independent documents — they are five acts of a single story:</p>'
    ),
    ('<div class="timeline-period">Livro 1</div>\n        <div class="timeline-title">Gênesis — As Origens</div>\n        <div class="timeline-text">Criação, queda, dilúvio, dispersão e as promessas patriarcais (Abraão, Isaque, Jacó, José). Estabelece o problema (pecado) e a solução prometida (aliança e bênção das nações).</div>',
     '<div class="timeline-period">Book 1</div>\n        <div class="timeline-title">Genesis — The Origins</div>\n        <div class="timeline-text">Creation, fall, flood, dispersion, and the patriarchal promises (Abraham, Isaac, Jacob, Joseph). Establishes the problem (sin) and the promised solution (covenant and blessing of the nations).</div>'),
    ('<div class="timeline-period">Livro 2</div>\n        <div class="timeline-title">Êxodo — A Libertação</div>\n        <div class="timeline-text">Opressão no Egito, chamado de Moisés, pragas, Páscoa, travessia do Mar, Sinai, Lei, Tabernáculo. Israel passa de escravos a povo da aliança.</div>',
     '<div class="timeline-period">Book 2</div>\n        <div class="timeline-title">Exodus — The Liberation</div>\n        <div class="timeline-text">Oppression in Egypt, calling of Moses, plagues, Passover, crossing of the Sea, Sinai, Law, Tabernacle. Israel passes from slaves to covenant people.</div>'),
    ('<div class="timeline-period">Livro 3</div>\n        <div class="timeline-title">Levítico — A Santidade</div>\n        <div class="timeline-text">Leis sacrificiais, sacerdócio, pureza, festas, Ano do Jubileu. Como o povo da aliança se aproxima e permanece diante de um Deus santo.</div>',
     '<div class="timeline-period">Book 3</div>\n        <div class="timeline-title">Leviticus — The Holiness</div>\n        <div class="timeline-text">Sacrificial laws, priesthood, purity, feasts, Year of Jubilee. How the covenant people draw near and remain before a holy God.</div>'),
    ('<div class="timeline-period">Livro 4</div>\n        <div class="timeline-title">Números — A Peregrinação</div>\n        <div class="timeline-text">Censo, jornada, rebeliões, julgamento da geração incrédula, formação da nova geração. O caminho entre a revelação e a herança.</div>',
     '<div class="timeline-period">Book 4</div>\n        <div class="timeline-title">Numbers — The Wandering</div>\n        <div class="timeline-text">Census, journey, rebellions, judgment of the unbelieving generation, formation of the new generation. The path between revelation and inheritance.</div>'),
    ('<div class="timeline-period">Livro 5</div>\n        <div class="timeline-title">Deuteronômio — A Renovação</div>\n        <div class="timeline-text">Discurso final de Moisés: recapitulação da lei, renovação da aliança, bênçãos e maldições, morte de Moisés. Israel na fronteira da herança, pronto para entrar.</div>',
     '<div class="timeline-period">Book 5</div>\n        <div class="timeline-title">Deuteronomy — The Renewal</div>\n        <div class="timeline-text">Moses\'s final discourse: recapitulation of the law, covenant renewal, blessings and curses, death of Moses. Israel at the boundary of the inheritance, ready to enter.</div>'),
    (
        '<h2>O Pentateuco no Cânon</h2>\n    <p>No cânon hebraico, a Torah é a primeira das três divisões: <strong>Torah</strong> (Lei), <strong>Nevi\'im</strong> (Profetas) e <strong>Ketuvim</strong> (Escritos) — o chamado <em>TaNaK</em>. A Torah tem precedência hermenêutica: todos os outros livros são lidos à sua luz. Jesus resumiu o cânon como "a lei de Moisés, os profetas e os salmos" (Lc 24.44) — confirmando esta estrutura tripartite.</p>',
        '<h2>The Pentateuch in the Canon</h2>\n    <p>In the Hebrew canon, the Torah is the first of three divisions: <strong>Torah</strong> (Law), <strong>Nevi\'im</strong> (Prophets), and <strong>Ketuvim</strong> (Writings) — the so-called <em>TaNaK</em>. The Torah has hermeneutical precedence: all other books are read in its light. Jesus summarized the canon as "the Law of Moses, the Prophets, and the Psalms" (Luke 24:44) — confirming this tripartite structure.</p>'
    ),
]

lines = []
for pt, en in additions:
    lines.append(f'out = out.replace(\n    {repr(pt)},\n    {repr(en)},\n    1\n)\n')

with open('gen_en_pentateuco.py', 'a', encoding='utf-8') as f:
    f.write('\n# ═══ deserto + teologia + nt + pentateuco ═══\n')
    f.writelines(lines)

print(f'Appended {len(lines)} replacements')
